### ISSUE TITLE
Updating the latest version on npm

### ISSUE THREAD

**Issue by player1537** [qwtel/create-element-x#4]
I saw that you recently fixed a bug that allows this to be used with the latest JSX transpiler (#3). Could you update the version on npm?

**Comment by qwtel** [comment]
it already is: https://www.npmjs.com/package/create-element-x

any issues remaing?

**Comment by player1537** [comment]
Ah, I see. I was using the previous version from npm ( https://www.npmjs.com/package/create-element-extended ) rather than the renamed version ( https://www.npmjs.com/package/create-element-x ).

Everything is resolved.
